"""
Shared constants grouped by responsibility.
"""

from .alignment import (
    ALIGNMENT_BATCH_SIZE,
    ALIGNMENT_FIELDS,
    ALIGNMENT_INSTRUCTION,
    ALIGNMENT_MAXIMUM_LENGTH,
    ALIGNMENT_MODEL,
    ALIGNMENT_MODELS,
    DEFAULT_INSTRUCTIONS,
    INSTRUCTIONS_PATH,
    RELATION_INSTRUCTIONS,
    TRANSLATION_RELATION,
)
from .extraction import (
    BATCH_SIZE,
    COMPRESSION_LEVEL,
    LANGUAGE,
    LANGUAGE_SECTION,
    PROCESSES,
    SPACY_PIPELINE,
)
from .upstream import (
    CHUNK_SIZE,
    DUMP_INDEX_URL,
    DUMP_STATUS_URL,
    DUMP_URL,
    KAIKKI_URL,
    TIMEOUT,
    USER_AGENT,
    WORDNET_INDEX_URL,
    WORDNET_URL,
)

__all__ = [
    "ALIGNMENT_BATCH_SIZE",
    "ALIGNMENT_FIELDS",
    "ALIGNMENT_INSTRUCTION",
    "ALIGNMENT_MAXIMUM_LENGTH",
    "ALIGNMENT_MODEL",
    "ALIGNMENT_MODELS",
    "BATCH_SIZE",
    "CHUNK_SIZE",
    "COMPRESSION_LEVEL",
    "DEFAULT_INSTRUCTIONS",
    "DUMP_INDEX_URL",
    "DUMP_STATUS_URL",
    "DUMP_URL",
    "INSTRUCTIONS_PATH",
    "KAIKKI_URL",
    "LANGUAGE",
    "LANGUAGE_SECTION",
    "PROCESSES",
    "RELATION_INSTRUCTIONS",
    "SPACY_PIPELINE",
    "TIMEOUT",
    "TRANSLATION_RELATION",
    "USER_AGENT",
    "WORDNET_INDEX_URL",
    "WORDNET_URL",
]
