"""Define prefixes classifying Wiktionary glosses."""

FORM_GLOSS_PREFIXES = frozenset(
    {
        "accusative of",
        "accusative singular of",
        "alternative plural of",
        "animate accusative plural",
        "animate accusative singular",
        "a plural of",
        "attributive form",
        "comparative degree of",
        "comparative form of",
        "dative of",
        "dative plural",
        "dative/prepositional singular of",
        "dative singular of",
        "definite nominative/accusative singular",
        "feminine plural",
        "feminine singular",
        "first-person plural",
        "first-person singular future",
        "first-person singular non-past",
        "first-person singular past",
        "first-person singular present",
        "genitive/accusative plural of",
        "genitive/accusative/prepositional plural of",
        "genitive/accusative singular of",
        "genitive/dative/prepositional singular",
        "genitive/dative/prepositional singular of",
        "genitive of",
        "genitive plural",
        "genitive/prepositional plural of",
        "genitive singular of",
        "imperfective and stem (or continuative) forms of",
        "inanimate accusative plural",
        "inflection of",
        "instrumental plural of",
        "instrumental singular",
        "locative singular of",
        "masculine plural",
        "masculine singular past",
        "neuter singular past",
        "nominative/accusative plural",
        "nominative plural",
        "past of",
        "past participle",
        "past tense of",
        "plural of",
        "plural past",
        "prepositional plural of",
        "prepositional singular of",
        "present participle of",
        "present participle and",
        "second-person",
        "second-person feminine",
        "second-person masculine",
        "second-person plural",
        "second-person singular simple",
        "second-person singular simple past",
        "second-person singular simple present",
        "short feminine singular",
        "short masculine singular",
        "short neuter singular",
        "short plural of",
        "short plural past",
        "simple past of",
        "simple past and",
        "simple past tense",
        "simple past tense and",
        "simple past tense of",
        "stem or continuative form of",
        "superlative form",
        "third-person feminine",
        "third-person masculine",
        "third-person plural",
        "third-person singular",
        "third-person singular simple",
        "third-person singular simple present",
    }
)
"""Identify inflection descriptions excluded from lexical senses."""

SYNONYM_GLOSS_PREFIXES = frozenset({"synonym", "synonym of"})
"""Identify synonym redirects excluded from lexical senses."""

VARIANT_GLOSS_PREFIXES = frozenset(
    {
        "abbreviation",
        "abbreviation of",
        "active participle of",
        "a diminutive of",
        "alternative form",
        "alternative form of",
        "alternative letter-case",
        "alternative letter-case form",
        "alternative letter-case form of",
        "alternative spelling of",
        "an aphetic form of",
        "anglicized form of",
        "aphetic form of",
        "archaic",
        "archaic form",
        "archaic form of",
        "archaic spelling",
        "archaic spelling of",
        "a transliteration",
        "dated form",
        "dated form of",
        "elative degree of",
        "elongated form of",
        "eye dialect",
        "eye dialect spelling",
        "eye dialect spelling of",
        "informal form of",
        "initialism of",
        "misspelling",
        "misspelling of",
        "non-oxford",
        "non-oxford british",
        "non-oxford british english",
        "non-oxford british english standard",
        "nonstandard form of",
        "nonstandard spelling of",
        "obsolete",
        "obsolete spelling",
        "obsolete spelling of",
        "passive participle of",
        "pronunciation spelling of",
        "rare form of",
        "rare spelling",
        "rare spelling of",
        "reduced form of",
        "representing a pronunciation of",
        "shortened form of",
        "short form of",
        "singulative of",
        "the condition",
        "this term needs a definition. please help out and",
        "this term needs a translation to english",
        "uncommon form of",
        "unstressed form of",
        "used other",
        "used other than",
        "used other than with",
        "verbal noun of",
    }
)
"""Identify variant descriptions and editorial placeholders."""
