"""
Exercise command-level inference and cached decision replay.
"""

import csv
import json
from collections.abc import Sequence
from compression import zstd
from pathlib import Path
from typing import cast, override

import pytest
from typer.testing import CliRunner

from wsc import cli
from wsc.collection import write_collection
from wsc.constants import ALIGNMENT_FIELDS
from wsc.files import Compression
from wsc.identifiers import translation_table_id
from wsc.models import POS, Lemma, Sense, TranslationTable
from wsc.models.alignment import (
    AlignmentTask,
    LanguageModel,
    ModelOutcome,
    ModelRequest,
    ModelSettings,
)
from wsc.reading import read_alignment_cache, read_lemmas


class Model:
    """
    Generate a valid association for the candidate supplied by the command.
    """

    def __init__(
        self,
        response: str | None = None,
    ) -> None:
        """
        Store an optional fixed response.

        Args:
            response: Fixed response for partial reuse tests.
        """
        self.response: str | None = response
        self.requests: list[ModelRequest] = []

    def generate(
        self,
        request: ModelRequest,
    ) -> str:
        """
        Associate the source with its only candidate.

        Args:
            request: Model request generated by the command.

        Returns:
            A translation or equivalent synset association.
        """
        self.requests.append(request)

        if self.response is not None:
            return self.response

        translation_target = translation_table_id("word.noun", "gloss")
        relation = (
            "translation" if translation_target in request.prompt else "equivalent"
        )
        target = translation_target if relation == "translation" else "synset"

        return json.dumps(
            {
                "s": [
                    {
                        "target_id": target,
                        "relation": relation,
                        "reason": "Same lexical meaning.",
                    },
                ],
            },
        )

    def generate_batch(
        self,
        requests: Sequence[ModelRequest],
    ) -> tuple[ModelOutcome, ...]:
        """
        Generate every response in a command inference batch.

        Args:
            requests: Rendered model requests.

        Returns:
            One successful outcome per request.
        """
        return tuple(ModelOutcome(self.generate(request)) for request in requests)


def test_aligns_compressed_collection_into_one_archive(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """
    Archive input and output preserve plain cache tables for reuse.

    Args:
        tmp_path: Isolated collection and alignment destinations.
        monkeypatch: Replacement for model loading.
    """
    table = TranslationTable(
        translation_table_id("word.noun", "gloss"),
        "gloss",
        {"it": frozenset({"parola"})},
    )
    lemma = Lemma(
        "word.noun",
        "word",
        POS.NOUN,
        senses=[Sense("s", ("meaning",))],
        translation_tables=(table,),
    )
    write_collection([lemma], tmp_path / "collection", {}, Compression.ZSTANDARD)

    def load_model(
        settings: ModelSettings,
    ) -> LanguageModel:
        """
        Supply a deterministic model for archived alignment.

        Args:
            settings: Inference settings supplied by the command.

        Returns:
            A local model producing one translation decision.
        """
        del settings

        return Model()

    monkeypatch.setattr(cli, "open_model", load_model)

    result = CliRunner().invoke(
        cli.app,
        [
            "align",
            str(tmp_path / "collection.tar.zst"),
            "--task",
            "translations",
            "--output-dir",
            str(tmp_path / "alignment"),
            "--cache-dir",
            str(tmp_path / "cache"),
            "--compression",
            "zst",
        ],
    )

    assert result.exit_code == 0, result.output
    assert (
        next(read_lemmas(tmp_path / "alignment.tar.zst")).senses[0].translation_table
        == table
    )
    cache_path = tmp_path / "cache" / "alignment" / "translations.tsv"
    assert cache_path.is_file()

    _ = cache_path.with_suffix(".tsv.zst").write_bytes(
        zstd.compress(cache_path.read_bytes())
    )
    cache_path.unlink()

    def reject_model(
        settings: ModelSettings,
    ) -> LanguageModel:
        """
        Reject model loading when every decision is cached.

        Args:
            settings: Unexpected inference settings.

        Raises:
            AssertionError: If cached alignment starts inference.
        """
        raise AssertionError(f"Unexpected model loading: {settings.model}")

    monkeypatch.setattr(cli, "open_model", reject_model)

    reused = CliRunner().invoke(
        cli.app,
        [
            "align",
            str(tmp_path / "collection.tar.zst"),
            "--task",
            "translations",
            "--output-dir",
            str(tmp_path / "alignment"),
            "--cache-dir",
            str(tmp_path / "cache"),
            "--compression",
            "zst",
            "--reuse",
        ],
    )

    assert reused.exit_code == 0, reused.output
    assert cache_path.is_file()


@pytest.mark.parametrize("tasks", [(AlignmentTask.TRANSLATIONS,), tuple(AlignmentTask)])
def test_replays_cached_alignment(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    tasks: tuple[AlignmentTask, ...],
) -> None:
    """
    Cached replay preserves the aligned collection and original input.
    """
    input_path = tmp_path / "input.jsonl"
    original_content = (
        json.dumps(
            {
                "id": "word.noun",
                "lemma": "word",
                "pos": "noun",
                "senses": [{"id": "s", "glosses": ["meaning"], "synonyms": ["term"]}],
                "translation_tables": [
                    {
                        "id": translation_table_id("word.noun", "gloss"),
                        "gloss": "gloss",
                        "translations": {"it": ["parola"]},
                    },
                ],
            },
        )
        + "\n"
    )
    _ = input_path.write_text(original_content, encoding="utf-8")

    synsets_path = tmp_path / "synsets.jsonl"
    _ = synsets_path.write_text(
        json.dumps(
            {
                "id": "synset",
                "pos": "noun",
                "glosses": ["meaning"],
                "members": {"source1": ["word"], "source2": ["word", "different_word"]},
            },
        )
        + "\n",
        encoding="utf-8",
    )

    def load_model(
        settings: ModelSettings,
    ) -> LanguageModel:
        """
        Replace weight loading while retaining model settings.

        Args:
            settings: Command inference configuration.

        Returns:
            An offline language model.
        """
        assert settings.temperature == 0.0
        assert settings.reasoning_parser == "qwen3"
        assert settings.chat_template_options == (("enable_thinking", False),)
        assert settings.engine_options == (("tensor_parallel_size", 4),)

        return Model()

    monkeypatch.setattr(cli, "open_model", load_model)

    arguments = [
        "align",
        str(input_path),
        "--output-dir",
        str(tmp_path / "output"),
        "--cache-dir",
        str(tmp_path / "cache"),
        "--synsets",
        str(synsets_path),
        "--reasoning-parser",
        "qwen3",
        "--chat-template-option",
        "enable_thinking=false",
        "--engine-option",
        "tensor_parallel_size=4",
        "--batch-size",
        "1",
    ]

    for task in tasks:
        arguments.extend(("--task", task))

    inference_result = CliRunner().invoke(cli.app, arguments)

    assert inference_result.exit_code == 0, inference_result.output
    assert "INFO wsc.cli: Writing alignment cache:" in inference_result.stderr
    assert not inference_result.stdout

    output_dir = tmp_path / "output"
    aligned_lemma = next(read_lemmas(output_dir / "senses.jsonl"))

    assert aligned_lemma.senses[0].translation_table == TranslationTable(
        translation_table_id("word.noun", "gloss"),
        "gloss",
        {"it": frozenset({"parola"})},
    )
    assert not aligned_lemma.translation_tables

    if AlignmentTask.SYNSETS in tasks:
        assert aligned_lemma.senses[0].synsets[0].synset_id == "synset"
        assert aligned_lemma.senses[0].synsets[0].sources == ("source1", "source2")

    cache_paths = list((tmp_path / "cache").glob("alignment/*.tsv"))

    assert {path.stem for path in cache_paths} == set(tasks)
    assert all(
        path.read_text(encoding="utf-8").splitlines()[0]
        == "alignment_id\tsource_id\ttarget_id\trelation\treason"
        for path in cache_paths
    )

    cached_content = {path: path.read_bytes() for path in cache_paths}

    def reject_model(
        settings: ModelSettings,
    ) -> LanguageModel:
        """
        Fail if replay attempts model inference.

        Args:
            settings: Unexpected model configuration.

        Raises:
            AssertionError: If a model is loaded.
        """
        raise AssertionError(f"Unexpected model loading: {settings.model}")

    monkeypatch.setattr(cli, "open_model", reject_model)
    replay_result = CliRunner().invoke(cli.app, [*arguments, "--reuse"])

    assert replay_result.exit_code == 0, replay_result.output
    assert next(read_lemmas(output_dir / "senses.jsonl")) == aligned_lemma
    assert input_path.read_text() == original_content
    assert {path: path.read_bytes() for path in cache_paths} == cached_content

    manifest = cast(
        dict[str, object],
        json.loads((output_dir / "manifest.json").read_text()),
    )
    files = cast(dict[str, object], manifest["files"])

    assert manifest["tasks"] == list(tasks)
    assert files["senses"] == "senses.jsonl"

    for task in tasks:
        report = cast(
            dict[str, object],
            json.loads((output_dir / "reports" / f"{task}.json").read_text()),
        )

        assert report["task"] == task
        assert report["senses"] == {
            "evaluated": 1,
            "aligned": 1,
            "unaligned": 0,
        }
        assert report["associations"] == 1
        assert report["relations"] == {
            "translation" if task == AlignmentTask.TRANSLATIONS else "equivalent": 1,
        }

    incompatible_result = CliRunner().invoke(
        cli.app,
        [*arguments, "--temperature", "0.5", "--reuse"],
    )

    assert incompatible_result.exit_code == 0, incompatible_result.output
    assert next(read_lemmas(output_dir / "senses.jsonl")) == aligned_lemma


def test_rejects_input_overwrite(
    tmp_path: Path,
) -> None:
    """
    In-place alignment fails before loading models.
    """
    input_path = tmp_path / "input.jsonl"
    _ = input_path.write_text("original", encoding="utf-8")
    result = CliRunner().invoke(
        cli.app,
        ["align", str(input_path), "--output-dir", str(input_path)],
    )

    assert result.exit_code != 0
    assert input_path.read_text() == "original"


def test_reuses_partial_alignment_cache(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """
    Reuse requests only sources absent from the task TSV.
    """
    input_path = tmp_path / "input.jsonl"
    first_target = translation_table_id("word.noun", "first")
    second_target = translation_table_id("word.noun", "second")
    _ = input_path.write_text(
        json.dumps(
            {
                "id": "word.noun",
                "lemma": "word",
                "pos": "noun",
                "senses": [
                    {"id": "s1", "glosses": ["first"]},
                    {"id": "s2", "glosses": ["second"]},
                ],
                "translation_tables": [
                    {
                        "id": first_target,
                        "gloss": "first",
                        "translations": {"it": ["uno"]},
                    },
                    {
                        "id": second_target,
                        "gloss": "second",
                        "translations": {"it": ["due"]},
                    },
                ],
            },
        )
        + "\n",
        encoding="utf-8",
    )

    cache_path = tmp_path / "cache" / "alignment" / "translations.tsv"
    cache_path.parent.mkdir(parents=True)

    with cache_path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream, delimiter="\t")
        writer.writerow(ALIGNMENT_FIELDS)
        writer.writerow(
            (
                "translations:word.noun",
                "s1",
                first_target,
                "translation",
                "The definitions express the same concept.",
            ),
        )

    model = Model(
        json.dumps(
            {
                "s2": [
                    {
                        "target_id": second_target,
                        "relation": "translation",
                        "reason": "The definitions express the same concept.",
                    },
                ],
            },
        ),
    )

    def load_model(
        settings: ModelSettings,
    ) -> LanguageModel:
        """
        Return the partial reuse model after deferred loading.

        Args:
            settings: Command inference configuration.

        Returns:
            Model recording the missing-source request.
        """
        del settings

        return model

    monkeypatch.setattr(cli, "open_model", load_model)

    result = CliRunner().invoke(
        cli.app,
        [
            "align",
            str(input_path),
            "--output-dir",
            str(tmp_path / "output"),
            "--task",
            "translations",
            "--cache-dir",
            str(tmp_path / "cache"),
            "--reuse",
        ],
    )

    assert result.exit_code == 0, result.output
    assert len(model.requests) == 1
    assert model.requests[0].schema["required"] == ["s2"]
    assert first_target not in model.requests[0].prompt
    assert second_target in model.requests[0].prompt

    (aligned,) = tuple(read_lemmas(tmp_path / "output" / "senses.jsonl"))

    assert aligned.senses[0].translation_table == TranslationTable(
        first_target,
        "first",
        {"it": frozenset({"uno"})},
    )
    assert aligned.senses[1].translation_table == TranslationTable(
        second_target,
        "second",
        {"it": frozenset({"due"})},
    )
    assert len(cache_path.read_text().splitlines()) == 3


def test_resumes_after_model_failure(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """
    A failed batch leaves earlier decisions in the ordinary TSV cache.
    """
    input_path = tmp_path / "input.jsonl"
    targets = {
        word: translation_table_id(f"{word}.noun", word) for word in ("first", "second")
    }
    records = (
        {
            "id": f"{word}.noun",
            "lemma": word,
            "pos": "noun",
            "senses": [{"id": f"{word}.noun.1", "glosses": [word]}],
            "translation_tables": [
                {
                    "id": targets[word],
                    "gloss": word,
                    "translations": {"it": [word]},
                },
            ],
        }
        for word in targets
    )
    _ = input_path.write_text(
        "".join(f"{json.dumps(record)}\n" for record in records),
        encoding="utf-8",
    )

    class FailingModel(Model):
        """
        Fail after one completed translation decision.
        """

        @override
        def generate_batch(
            self,
            requests: Sequence[ModelRequest],
        ) -> tuple[ModelOutcome, ...]:
            """
            Return one decision before simulating an engine failure.

            Args:
                requests: Single-request batch supplied by the aligner.

            Returns:
                First successful outcome in submission order.

            Raises:
                RuntimeError: When the second batch is submitted.
            """
            self.requests.extend(requests)

            if len(self.requests) > 1:
                raise RuntimeError("engine died")

            return (
                ModelOutcome(
                    json.dumps(
                        {
                            "first.noun.1": [
                                {
                                    "target_id": targets["first"],
                                    "relation": "translation",
                                    "reason": "Same meaning.",
                                },
                            ],
                        },
                    ),
                ),
            )

    failing_model = FailingModel()

    def load_failing_model(
        settings: ModelSettings,
    ) -> LanguageModel:
        """
        Return the model that fails on its second request.

        Args:
            settings: Unused inference configuration.

        Returns:
            The test model.
        """
        del settings

        return failing_model

    monkeypatch.setattr(cli, "open_model", load_failing_model)
    arguments = [
        "align",
        str(input_path),
        "--task",
        "translations",
        "--batch-size",
        "1",
        "--cache-dir",
        str(tmp_path / "cache"),
        "--output-dir",
        str(tmp_path / "output"),
    ]

    failed = CliRunner().invoke(cli.app, arguments)

    assert failed.exit_code != 0
    assert isinstance(failed.exception, RuntimeError)
    assert str(failed.exception) == "engine died"
    assert failed.exception.__notes__ == [
        "Failed alignment batch (1): translations:second.noun"
    ]

    cache_path = tmp_path / "cache" / "alignment" / "translations.tsv"
    assert cache_path.exists()
    assert not list(cache_path.parent.glob("*.part"))
    assert set(read_alignment_cache(cache_path)) == {"translations:first.noun"}

    class ResumeModel(Model):
        """
        Resolve only the still-uncached second lemma.
        """

        @override
        def generate_batch(
            self,
            requests: Sequence[ModelRequest],
        ) -> tuple[ModelOutcome, ...]:
            """
            Return the remaining translation association.

            Args:
                requests: Single uncached alignment request.

            Returns:
                One successful model outcome.
            """
            self.requests.extend(requests)

            return (
                ModelOutcome(
                    json.dumps(
                        {
                            "second.noun.1": [
                                {
                                    "target_id": targets["second"],
                                    "relation": "translation",
                                    "reason": "Same meaning.",
                                },
                            ],
                        },
                    ),
                ),
            )

    resume_model = ResumeModel()

    def load_resume_model(
        settings: ModelSettings,
    ) -> LanguageModel:
        """
        Return the model resolving the remaining request.

        Args:
            settings: Unused inference configuration.

        Returns:
            The test model.
        """
        del settings

        return resume_model

    monkeypatch.setattr(cli, "open_model", load_resume_model)

    resumed = CliRunner().invoke(cli.app, [*arguments, "--reuse"])

    assert resumed.exit_code == 0, resumed.output
    assert len(resume_model.requests) == 1
    assert resume_model.requests[0].schema["required"] == ["second.noun.1"]
    assert set(read_alignment_cache(cache_path)) == {
        "translations:first.noun",
        "translations:second.noun",
    }
